### ISSUE TITLE
Problem Mapping Customers Updates WebAPI Result to PostCustomer of sdk

### ISSUE THREAD

**Issue by nupmarin** [contactlab/contacthub-sdk-dotnet#1]
Salve,
come sapete utilizzando la chiamata alla WebApi:

https://api.contactlab.it/hub/v1/workspaces/{0}/updates?entity=CUSTOMER

ottengo tutti gli ultimi aggionamenti della customer base.

Per mappare la risposta Json della webApi ho creato un oggetto strutturato che come foglia ha il "PostCustomer" dell'sdk ed in alcuni casi va tuttop bene mentre in altri ho dei problemi (per ora dipende dal workspace a cui mi collego).

La problematica è la seguente:

risporto un estratto del Json di risposta della WebAPI nel caso in cui tutto è ok:

{
      "operation": "DELETE",
      "entity": {
        "type": "CUSTOMER",
        "data": {
          "id": "57237dd4-b529-413f-9d68-b34747394731",
          "intId": 50001995,
          "nodeId": "a04350dc-bfa3-4c6b-a7dd-512daa1fadce",
          "externalId": "de82e2d5-7e76-47f4-a74d-f6208f72e035",
          "extra": null,
          "registeredAt": "2018-04-18T08:42:41.542+0000",
          "updatedAt": "2018-07-11T12:48:38.164+0000",
          "enabled": true,
          "base": {
            "pictureUrl": null,
            "title": "Mr",
            "prefix": null,
            "firstName": "FirstName405",
            "lastName": "LastName405",
            "middleName": "MiddleName405",
            "gender": "M",
            "dob": null,
            "locale": null,
            "timezone": "Europe/Rome",
            "contacts": {
              "email": "FirstName.LastName405@yourdomain.com",
              "fax": null,
              "mobilePhone": null,
              "phone": null,
              "otherContacts": [],
              "mobileDevices": []
            },
            "address": null,
            "credential": null,
            "educations": [],
            "likes": [],
            "socialProfile": null,
            "jobs": [],
            "subscriptions": []
          },
          "extended": null,
          "tags": null,
          "sourceInfo": {
            "registeredBy": "46d5a7d9-16e9-4f0e-a82b-e75432ce08a9",
            "updatedBy": "46d5a7d9-16e9-4f0e-a82b-e75432ce08a9"
          },
          "consents": null,
          "version": 100014451
        }
      }
    },

Io cerco di mappare il Json con il seguente oggetto, che è il "PostCustomer" dell'SDK:

 public class PostCustomer
    {
        public PostCustomer();

        public string externalId { get; set; }
        public string nodeId { get; set; }
        public BaseProperties @base { get; set; }
        public ConsentsProperties consents { get; set; }
        [JsonIgnore]
        [JsonProperty("_extended")]
        public List<ExtendedProperty> extended { get; set; }
        [JsonProperty("extended")]
        public object _extended { get; set; }
        public string extra { get; set; }
        public Tags tags { get; set; }
        public bool? enabled { get; set; }
    }

notiamo che essendo la proprietà "consents" sempre "null"  non abbiamo alcun problema di conversione da json ad oggetto,

Di seguito l'estratto del Json che porta all'errore:

{
      "operation": "UPDATE",
      "entity": {
        "type": "CUSTOMER",
        "data": {
          "id": "77f2f0eb-091a-4b88-a167-c33325dede87",
          "intId": 9607,
          "nodeId": "1586479e-f0c0-4a6f-8fbc-823fd842c46f",
          "externalId": "4830a76005e15704412b420f1cc90d04",
          "extra": null,
          "registeredAt": "2017-03-09T00:00:29.625+0000",
          "updatedAt": "2018-05-18T09:57:54.832+0000",
          "enabled": true,
          "base": {
            "pictureUrl": "https://randomuser.me/api/portraits/thumb/men/9.jpg",
            "title": "mr",
            "prefix": null,
            "firstName": "ronald",
            "lastName": "marshall",
            "middleName": null,
            "gender": "male",
            "dob": "1989-10-10",
            "locale": null,
            "timezone": null,
            "contacts": {
              "email": "ronald.marshall@example.com",
              "fax": null,
              "mobilePhone": "081-746-4878",
              "phone": "051-761-7746",
              "otherContacts": [],
              "mobileDevices": []
            },
            "address": {
              "street": "3181 school lane",
              "city": "shannon",
              "country": "IE",
              "province": "carlow",
              "region": null,
              "zip": "99069",
              "geo": null
            },
            "credential": {
              "username": "smallleopard887",
              "password": "bonbon"
            },
            "educations": [],
            "likes": [
              {
                "id": "1",
                "category": "App Page",
                "name": "Beme",
                "createdTime": null
              },
              {
                "id": "2",
                "category": "Artist",
                "name": "Banksy",
                "createdTime": null
              },
              {
                "id": "3",
                "category": "Author",
                "name": "Fabio Volo",
                "createdTime": null
              },
              {
                "id": "4",
                "category": "Clothing",
                "name": "Siviglia",
                "createdTime": null
              },
              {
                "id": "5",
                "category": "App Page",
                "name": "Whatsapp",
                "createdTime": null
              }
            ],
            "socialProfile": {
              "facebook": null,
              "google": "https://www.google.com/ronald",
              "instagram": null,
              "linkedin": "https://www.linkedin.com/ronald",
              "qzone": "https://www.qzone.com/ronald",
              "twitter": "https://www.twitter.com/ronald"
            },
            "jobs": [],
            "subscriptions": [
              {
                "id": "NEWSLETTER",
                "name": "Newsletter italia",
                "type": null,
                "kind": "DIGITAL_MESSAGE",
                "subscribed": true,
                "startDate": null,
                "endDate": null,
                "subscriberId": null,
                "registeredAt": null,
                "updatedAt": null,
                "preferences": []
              }
            ]
          },
          "extended": {
            "lifetimevalue": 3900,
            "productcategoriespurchased": [
              "CHILD",
              "AUTUMN",
              "MAN",
              "SUMMER",
              "WOMAN",
              "SPRING"
            ]
          },
          "tags": { "auto": ["TECHNOLOGY"], "manual": ["google", "dog"] },
          "sourceInfo": {
            "registeredBy": "51c65d03-5ce1-4e93-8f2d-8f2e93acc324",
            "updatedBy": "users-source"
          },
          "consents": {
            "disclaimer": null,
            "marketing": null,
            "profiling": {
              "classic": {
                "status": true,
                "limitation": null,
                "objection": null
              },
              "online": null
            },
            "softSpam": null,
            "thirdPartyTransfer": null
          },
          "version": 100027596
        }
      }
    },

la proprietà "consents" veine mappata con il seguente oggetto:

 public class ConsentsProperties
    {
        public ConsentsProperties();

        public Disclaimer disclaimer { get; set; }
        public Marketing marketing { get; set; }
        public Profiling profiling { get; set; }
        public SoftSpam softSpam { get; set; }
        public ThirdPartyTransfer thirdPartyTransfer { get; set; }
    }
che contiene

 public class Profiling
    {
        public Profiling();

        public Classic classic { get; set; }
        public Online online { get; set; }
    }
che contiene  

public class Classic
    {
        public Classic();

        public bool status { get; set; }
        public bool limitation { get; set; }
        public bool objection { get; set; }
    }

come possiamo notare dal seguente Json:

  "consents": {
            "disclaimer": null,
            "marketing": null,
            "profiling": {
              "classic": {
                "status": true,
                "limitation": null,
                "objection": null
              },
              "online": null
            },
            "softSpam": null,
            "thirdPartyTransfer": null
          },
          "version": 100027596
        }

la proprietà " public bool limitation { get; set; }" non è nullabile (bool?), mentre nella risposta ci arriva    "limitation": null,", stessa cosa per " "objection": null" il che porta ad una eccezione nel mapping.

Spero di essere stato chiaro.

Grazie

**Comment by psantori** [comment]
Fixed by commit f29671b97444cd2cab1ac5bb5520c3d65f7cef99 and 8aca4354464812f4298db86debbe58c39bc13f77
